version: '3.1'

services:

    db:
      image: postgres
      environment:
        POSTGRES_USER: django
        POSTGRES_PASSWORD: passwd
      ports:
        - 127.0.0.1:5432:5432

    adminer:
      image: adminer
      ports:
        - 127.0.0.1:8080:8080
      
    # Redis
    redis:
        image: redis:latest
        hostname: redis
        ports:
          - 127.0.0.1:6379:6379

    # RabbitMQ
    rabbit:
        hostname: rabbit
        image: rabbitmq:3.6.9
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
                - 127.0.0.1:5672:5672
                - 127.0.0.1:15672:15672

#    celery1:
#        build: ./
#        command: celery worker --app=videocatalog --loglevel=info --logfile=logs/celery.log
#        volumes:
#          - ./:/usr/src/app
#        environment:
#          - DEBUG=1
#          - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#        depends_on:
#          - rabbit
