# Generated by Django 4.0 on 2022-01-05 17:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_status_alter_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=core.models._get_video_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
