# Generated by Django 4.0 on 2022-01-09 14:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_video_cover_alter_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.FileField(blank=True, default='', upload_to=core.models._get_video_cover_upload_path),
            preserve_default=False,
        ),
    ]
